### ISSUE TITLE
invalid characters in path (route) lead to jackrabbit xml parser error

### ISSUE THREAD

**Issue by joiz** [symfony-cmf/Routing#145] opened 2015-09-09 15:20 UTC
requesting a cmf url of the form http://joiz.lo/main_dev.php/[[dsfdsfsdfsd]] leads to the error message

Warning: DOMDocument::loadXML(): AttValue: &quot; or ' expected in Entity, line: 1
500 Internal Server Error - ContextErrorException

Stack Trace
in /var/www/joiz.lo/vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Request.php at line 685   -
        // create new DOMDocument and load the response text.
        $dom = new DOMDocument();
        $dom->loadXML($xml);
        return $dom;

ok - you can blame the angular developers and make them fix their code - but i think it would be also a good idea to add some logic which regcognises a path which will most likely produce a error in jackrabbit route lookup and return straight a 404 instread of bothering the jackrabbit first

**Comment by lsmith77** [comment] 2015-09-09 15:21
I think we should check if we have a valid path before even calling the PHPCR layer

**Comment by dbu** [comment] 2016-01-09 12:57
this is fixed in newer versions of phpcr-odm. i debugged the situtation with the current https://github.com/symfony-cmf/cmf-sandbox and was not able to reproduce the issue. the RoutingBundle\Doctrine\Phpcr\RouteProvider::getRouteCollectionForRequest sees /cms/routes/[[dsfdsfdfsd]] as a candidate, but after $routes = $dm->findMany($this->className, $candidates);, the $routes only contain /cms/routes and /cms/simple. this leads to a regular 404 which is the expected behaviour.

**Closed by dbu** 2016-01-09 12:57 UTC

**Comment by joiz** [comment] 2016-01-12 16:41
Can i use the  phpcr-odm 1.3 with CMF 1.2 ?

**Comment by dbu** [comment] 2016-01-13 07:28
i would of course try it out first, but i guess it should work, yes.
there are a few more strict checks in 1.3, so maybe you will see some
error messages in places. just open phpcr-odm tickets when you see
something.
